### ISSUE TITLE
sqlite-net

### ISSUE THREAD

**Issue by eblabs** [heshuimu/SimpleBinding#1]
Hi,
Sorry, I was trying to contact you about your fork of sqlite-net for unity. [sqlite-net](https://github.com/heshuimu/sqlite-net)
I just wanted to ask, aside from copying in the SQLite.cs file. How do I actually install the sqlite3 plugin?
Thanks for any guidance, and sorry again for posting on an unrelated repo!!

**Comment by heshuimu** [comment]
@eblabs You only need to grab the official sqlite3 source code. There is this "amalgamation" version of the source code where all codes are bundled into a single C source file. 

https://www.sqlite.org/download.html

Drop it into the Unity project and it will automatically built alongside other code when you use IL2CPP. Do note that this ONLY works with IL2CPP.

**Comment by eblabs** [comment]
Thanks for the quick reply! Ah ok cool, I switched to IL2CPP as well.

I think I have another problem though, Im seeing this error. Any ideas?
`DllNotFoundException: sqlite3 assembly:<unknown assembly> type:<unknown type> member:(null)
SQLite.SQLiteConnection..ctor (SQLite.SQLiteConnectionString connectionString) (at Assets/Freeride/Scripts/SQLITE/SQLite.cs:293)
SQLite.SQLiteConnection..ctor (System.String databasePath, System.Boolean storeDateTimeAsTicks) (at Assets/Freeride/Scripts/SQLITE/SQLite.cs:252)
SQLVariableStorage.Start () (at Assets/Freeride/Scripts/Dialog/SQLVariableStorage.cs:18)`

**Comment by heshuimu** [comment]
Were you running this in Editor? You'll need to have a copy of sqlite3 installed on your computer to run in editor, because Editor Play mode does not use IL2CPP. 

I assume you are not on macOS because it has a copy of `libsqlite3` installed, so things work for me. I only develop on macOS so I have not tried anything else myself. For Windows Standalone and Editor you probably have to add a copy of the official sqlite3.dll to your Unity project.

**Comment by eblabs** [comment]
Ah, thanks for that. I was indeed running it in the editor. Thanks so much for clarifying that!~ 

Ill install the windows DLLs for it for local testing. Thanks again for your time!
